apiVersion: apps/v1
kind: Deployment
metadata:
  name: RollingUpdate-deployment
  labels:
    app: helloserver
spec:
  replicas: 8
  selector:
    matchLabels:
      app: helloserver
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloserver
    spec:
      containers:
      - name: helloserver
        image: khaledeltaweel/k8s-web-server
        # image: khaledeltaweel/k8s-web-server:1.0
        ports:
        - containerPort: 3000